// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2wLFfO_A-mogXZM6xaUEMdIUQXLPUSUE',
    appId: '1:351766027825:web:eb9581369e6bb86df2ff10',
    messagingSenderId: '351766027825',
    projectId: 'bloodbank-93d85',
    authDomain: 'bloodbank-93d85.firebaseapp.com',
    storageBucket: 'bloodbank-93d85.appspot.com',
    measurementId: 'G-3C4LHLDYB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-k0A-IYH51t9Psv2y0EMPfkkJCYgMZ18',
    appId: '1:351766027825:android:c4f983f82bac6480f2ff10',
    messagingSenderId: '351766027825',
    projectId: 'bloodbank-93d85',
    storageBucket: 'bloodbank-93d85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ249ttQJCGcZadtExWyhqvJPjWQUhN5U',
    appId: '1:351766027825:ios:c4b5209af3c44fd7f2ff10',
    messagingSenderId: '351766027825',
    projectId: 'bloodbank-93d85',
    storageBucket: 'bloodbank-93d85.appspot.com',
    iosClientId: '351766027825-h498gg2id4qcr8dtrlq14qd7siupc2n6.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDontaionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ249ttQJCGcZadtExWyhqvJPjWQUhN5U',
    appId: '1:351766027825:ios:66fc13279eadd618f2ff10',
    messagingSenderId: '351766027825',
    projectId: 'bloodbank-93d85',
    storageBucket: 'bloodbank-93d85.appspot.com',
    iosClientId: '351766027825-f9loqlapiis46ec454tq948ee2i0biqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodDontaionApp.RunnerTests',
  );
}
